version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://reviewassist:password@db:5432/reviewassist_dev
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - db
      - redis
    command: python src/main.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=reviewassist_dev
      - POSTGRES_USER=reviewassist
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:

